// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package cmd

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *accessEntry) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "b":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Bins")
				return
			}
			if cap(z.Bins) >= int(zb0002) {
				z.Bins = (z.Bins)[:zb0002]
			} else {
				z.Bins = make([]uint32, zb0002)
			}
			for za0001 := range z.Bins {
				z.Bins[za0001], err = dc.ReadUint32()
				if err != nil {
					err = msgp.WrapError(err, "Bins", za0001)
					return
				}
			}
		case "h":
			z.HeadAt, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "HeadAt")
				return
			}
		case "l":
			z.LastAt, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "LastAt")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *accessEntry) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "b"
	err = en.Append(0x83, 0xa1, 0x62)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Bins)))
	if err != nil {
		err = msgp.WrapError(err, "Bins")
		return
	}
	for za0001 := range z.Bins {
		err = en.WriteUint32(z.Bins[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Bins", za0001)
			return
		}
	}
	// write "h"
	err = en.Append(0xa1, 0x68)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.HeadAt)
	if err != nil {
		err = msgp.WrapError(err, "HeadAt")
		return
	}
	// write "l"
	err = en.Append(0xa1, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.LastAt)
	if err != nil {
		err = msgp.WrapError(err, "LastAt")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *accessEntry) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "b"
	o = append(o, 0x83, 0xa1, 0x62)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Bins)))
	for za0001 := range z.Bins {
		o = msgp.AppendUint32(o, z.Bins[za0001])
	}
	// string "h"
	o = append(o, 0xa1, 0x68)
	o = msgp.AppendInt64(o, z.HeadAt)
	// string "l"
	o = append(o, 0xa1, 0x6c)
	o = msgp.AppendInt64(o, z.LastAt)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *accessEntry) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "b":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Bins")
				return
			}
			if cap(z.Bins) >= int(zb0002) {
				z.Bins = (z.Bins)[:zb0002]
			} else {
				z.Bins = make([]uint32, zb0002)
			}
			for za0001 := range z.Bins {
				z.Bins[za0001], bts, err = msgp.ReadUint32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Bins", za0001)
					return
				}
			}
		case "h":
			z.HeadAt, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "HeadAt")
				return
			}
		case "l":
			z.LastAt, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LastAt")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *accessEntry) Msgsize() (s int) {
	s = 1 + 2 + msgp.ArrayHeaderSize + (len(z.Bins) * (msgp.Uint32Size)) + 2 + msgp.Int64Size + 2 + msgp.Int64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *accessShard) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "u":
			z.UpdatedAt, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "UpdatedAt")
				return
			}
		case "bw":
			z.BinWidth, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "BinWidth")
				return
			}
		case "e":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Entries")
				return
			}
			if z.Entries == nil {
				z.Entries = make(map[string]accessEntry, zb0002)
			} else if len(z.Entries) > 0 {
				clear(z.Entries)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Entries")
					return
				}
				var za0002 accessEntry
				err = za0002.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Entries", za0001)
					return
				}
				z.Entries[za0001] = za0002
			}
		case "d":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Demote")
				return
			}
			if cap(z.Demote) >= int(zb0003) {
				z.Demote = (z.Demote)[:zb0003]
			} else {
				z.Demote = make([]demoteCandidate, zb0003)
			}
			for za0003 := range z.Demote {
				var zb0004 uint32
				zb0004, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Demote", za0003)
					return
				}
				for zb0004 > 0 {
					zb0004--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "Demote", za0003)
						return
					}
					switch msgp.UnsafeString(field) {
					case "b":
						z.Demote[za0003].Bucket, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "Demote", za0003, "Bucket")
							return
						}
					case "o":
						z.Demote[za0003].Object, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "Demote", za0003, "Object")
							return
						}
					case "p":
						z.Demote[za0003].Pool, err = dc.ReadInt()
						if err != nil {
							err = msgp.WrapError(err, "Demote", za0003, "Pool")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "Demote", za0003)
							return
						}
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *accessShard) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "u"
	err = en.Append(0x84, 0xa1, 0x75)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.UpdatedAt)
	if err != nil {
		err = msgp.WrapError(err, "UpdatedAt")
		return
	}
	// write "bw"
	err = en.Append(0xa2, 0x62, 0x77)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.BinWidth)
	if err != nil {
		err = msgp.WrapError(err, "BinWidth")
		return
	}
	// write "e"
	err = en.Append(0xa1, 0x65)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Entries)))
	if err != nil {
		err = msgp.WrapError(err, "Entries")
		return
	}
	for za0001, za0002 := range z.Entries {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "Entries")
			return
		}
		err = za0002.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Entries", za0001)
			return
		}
	}
	// write "d"
	err = en.Append(0xa1, 0x64)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Demote)))
	if err != nil {
		err = msgp.WrapError(err, "Demote")
		return
	}
	for za0003 := range z.Demote {
		// map header, size 3
		// write "b"
		err = en.Append(0x83, 0xa1, 0x62)
		if err != nil {
			return
		}
		err = en.WriteString(z.Demote[za0003].Bucket)
		if err != nil {
			err = msgp.WrapError(err, "Demote", za0003, "Bucket")
			return
		}
		// write "o"
		err = en.Append(0xa1, 0x6f)
		if err != nil {
			return
		}
		err = en.WriteString(z.Demote[za0003].Object)
		if err != nil {
			err = msgp.WrapError(err, "Demote", za0003, "Object")
			return
		}
		// write "p"
		err = en.Append(0xa1, 0x70)
		if err != nil {
			return
		}
		err = en.WriteInt(z.Demote[za0003].Pool)
		if err != nil {
			err = msgp.WrapError(err, "Demote", za0003, "Pool")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *accessShard) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "u"
	o = append(o, 0x84, 0xa1, 0x75)
	o = msgp.AppendInt64(o, z.UpdatedAt)
	// string "bw"
	o = append(o, 0xa2, 0x62, 0x77)
	o = msgp.AppendInt64(o, z.BinWidth)
	// string "e"
	o = append(o, 0xa1, 0x65)
	o = msgp.AppendMapHeader(o, uint32(len(z.Entries)))
	for za0001, za0002 := range z.Entries {
		o = msgp.AppendString(o, za0001)
		o, err = za0002.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Entries", za0001)
			return
		}
	}
	// string "d"
	o = append(o, 0xa1, 0x64)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Demote)))
	for za0003 := range z.Demote {
		// map header, size 3
		// string "b"
		o = append(o, 0x83, 0xa1, 0x62)
		o = msgp.AppendString(o, z.Demote[za0003].Bucket)
		// string "o"
		o = append(o, 0xa1, 0x6f)
		o = msgp.AppendString(o, z.Demote[za0003].Object)
		// string "p"
		o = append(o, 0xa1, 0x70)
		o = msgp.AppendInt(o, z.Demote[za0003].Pool)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *accessShard) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "u":
			z.UpdatedAt, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UpdatedAt")
				return
			}
		case "bw":
			z.BinWidth, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BinWidth")
				return
			}
		case "e":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Entries")
				return
			}
			if z.Entries == nil {
				z.Entries = make(map[string]accessEntry, zb0002)
			} else if len(z.Entries) > 0 {
				clear(z.Entries)
			}
			for zb0002 > 0 {
				var za0002 accessEntry
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Entries")
					return
				}
				bts, err = za0002.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Entries", za0001)
					return
				}
				z.Entries[za0001] = za0002
			}
		case "d":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Demote")
				return
			}
			if cap(z.Demote) >= int(zb0003) {
				z.Demote = (z.Demote)[:zb0003]
			} else {
				z.Demote = make([]demoteCandidate, zb0003)
			}
			for za0003 := range z.Demote {
				var zb0004 uint32
				zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Demote", za0003)
					return
				}
				for zb0004 > 0 {
					zb0004--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "Demote", za0003)
						return
					}
					switch msgp.UnsafeString(field) {
					case "b":
						z.Demote[za0003].Bucket, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Demote", za0003, "Bucket")
							return
						}
					case "o":
						z.Demote[za0003].Object, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Demote", za0003, "Object")
							return
						}
					case "p":
						z.Demote[za0003].Pool, bts, err = msgp.ReadIntBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Demote", za0003, "Pool")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "Demote", za0003)
							return
						}
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *accessShard) Msgsize() (s int) {
	s = 1 + 2 + msgp.Int64Size + 3 + msgp.Int64Size + 2 + msgp.MapHeaderSize
	if z.Entries != nil {
		for za0001, za0002 := range z.Entries {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + za0002.Msgsize()
		}
	}
	s += 2 + msgp.ArrayHeaderSize
	for za0003 := range z.Demote {
		s += 1 + 2 + msgp.StringPrefixSize + len(z.Demote[za0003].Bucket) + 2 + msgp.StringPrefixSize + len(z.Demote[za0003].Object) + 2 + msgp.IntSize
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *demoteCandidate) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "b":
			z.Bucket, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Bucket")
				return
			}
		case "o":
			z.Object, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Object")
				return
			}
		case "p":
			z.Pool, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Pool")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z demoteCandidate) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "b"
	err = en.Append(0x83, 0xa1, 0x62)
	if err != nil {
		return
	}
	err = en.WriteString(z.Bucket)
	if err != nil {
		err = msgp.WrapError(err, "Bucket")
		return
	}
	// write "o"
	err = en.Append(0xa1, 0x6f)
	if err != nil {
		return
	}
	err = en.WriteString(z.Object)
	if err != nil {
		err = msgp.WrapError(err, "Object")
		return
	}
	// write "p"
	err = en.Append(0xa1, 0x70)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Pool)
	if err != nil {
		err = msgp.WrapError(err, "Pool")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z demoteCandidate) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "b"
	o = append(o, 0x83, 0xa1, 0x62)
	o = msgp.AppendString(o, z.Bucket)
	// string "o"
	o = append(o, 0xa1, 0x6f)
	o = msgp.AppendString(o, z.Object)
	// string "p"
	o = append(o, 0xa1, 0x70)
	o = msgp.AppendInt(o, z.Pool)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *demoteCandidate) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "b":
			z.Bucket, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Bucket")
				return
			}
		case "o":
			z.Object, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Object")
				return
			}
		case "p":
			z.Pool, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Pool")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z demoteCandidate) Msgsize() (s int) {
	s = 1 + 2 + msgp.StringPrefixSize + len(z.Bucket) + 2 + msgp.StringPrefixSize + len(z.Object) + 2 + msgp.IntSize
	return
}
